KidsAreaApp/Controllers/HoursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KidsAreaApp.Models;
using Microsoft.AspNetCore.Authorization;
using KidsAreaApp.Utility;

namespace KidsAreaApp.Controllers
{
    [Authorize(Roles = SD.Admin +","+ SD.SupAdmin)]
    public class HoursController : Controller
    {
        private readonly AppDbContext _context;

        public HoursController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Hours
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hours.ToListAsync());
        }      

        // GET: Hours/Create
        public IActionResult Create()
        {
            if (_context.Hours.Count()>0)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HourId,HourPrice")] Hour hour)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hour);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hour);
        }

        // GET: Hours/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hour = await _context.Hours.FindAsync(id);
            if (hour == null)
            {
                return NotFound();
            }
            return View(hour);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HourId,HourPrice")] Hour hour)
        {
            if (id != hour.HourId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hour);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HourExists(hour.HourId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hour);
        }

        // GET: Hours/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hour = await _context.Hours
                .FirstOrDefaultAsync(m => m.HourId == id);
            if (hour == null)
            {
                return NotFound();
            }

            return View(hour);
        }

        // POST: Hours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hour = await _context.Hours.FindAsync(id);
            _context.Hours.Remove(hour);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HourExists(int id)
        {
            return _context.Hours.Any(e => e.HourId == id);
        }
    }
}

KidsAreaApp/Controllers/UsersController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using KidsAreaApp.Services;
using KidsAreaApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace KidsAreaApp.Controllers
{
    [Authorize(Roles = SD.Admin+","+SD.SupAdmin)]
    public class UsersController : Controller
    {
        private readonly IUserService _userService;

        public UsersController(IUserService userService)
        {
            this._userService = userService;
        }
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = ((ClaimsIdentity)this.User.Identity);
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (User.IsInRole(SD.SupAdmin))
            {
                return View(await _userService.GetUsersForSupAdmin(claim));
            }

            return View(await _userService.GetUsersExceptCurrentUser(claim));
        }
        public async Task<IActionResult> Lock(string id)
        {
            if (id==null)
            {
                return NotFound();
            }
            if (await _userService.UserLock(id))
            {
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }
        public async Task<IActionResult> UnLock(string id)
        {
            if (id==null)
            {
                return NotFound();
            }
            if (await _userService.UserUnLock(id))
            {
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }

    }
}

KidsAreaApp/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<h2 class="text-danger">Not Found</h2>
<a class="btn btn-primary text-white" href="/">Go Back</a>

KidsAreaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kids Area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"  asp-append-version="true"/>
</head>
<body style="background-image:url('/Images/KidsAreaBack.jpg');background-size:cover;position:center">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Kids Area</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(KidsAreaApp.Utility.SD.Admin) || User.IsInRole(KidsAreaApp.Utility.SD.SupAdmin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Hours" asp-action="Index">Hour Management</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Users" asp-action="Index">Users Management</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="ReservationTransactions">Transactions</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" id="main">
            <main role="main" class="border backgroundWhiteLayout pb-3">
                @RenderBody()
            </main>
            </div>
        <footer class="border-top footer bg-dark text-muted">
            <div class="container text-white">
                &copy; @DateTime.UtcNow.Year - Kids Area
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>